# Generated by Django 5.2.6 on 2026-01-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_order_content_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_last_5',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
