# Generated by Django 5.2.6 on 2026-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gift_box',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paper_bag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
